"""empty message

Revision ID: a85db272f841
Revises: fa2913650e34
Create Date: 2022-04-03 19:02:14.843560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85db272f841'
down_revision = 'fa2913650e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('looking_venues', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=False))
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('looking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('venues', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venues', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venues', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venues', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venues', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('venues', 'description')
    op.drop_column('venues', 'looking_talent')
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'description')
    op.drop_column('artists', 'looking_venues')
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
